### ISSUE TITLE
Having trouble using composeVip on Windows

### ISSUE THREAD

**Issue by ArvinB** [vipconsult/composeVip#1]
I'm using Docker for Windows and have a Windows NFS share locally.

Can explicit instructions be given to this novice on what commands to use after doing the 'docker pull'?

**Comment by krasi-georgiev** [comment]
this is not meant for public use :) I am using this for a web server within our company.

**Comment by ArvinB** [comment]
No worries, I was just trying to get something to work using Docker for Windows against a Linux / Ubuntu Docker container to simply map a directory to an NFS share on the host. This one has had me stumped for about a month now and I have all but given up. Any suggestions?
